// GENERATED by tools/sprites-font.mjs — do not edit by hand.
// Index of each glyph in the baked 'pxfont' strip.
export const FONT_ORDER = ["0","1","2","3","4","5","6","7","8","9","A","B","C","D","E","F","G","H","I","J","K","L","M","N","O","P","Q","R","S","T","U","V","W","X","Y","Z"," ","-",".",":","/","!","*","<",">","+","=","%","#","'"] as const;

export function fontIndex(ch: string): number {
  const i = (FONT_ORDER as readonly string[]).indexOf(ch);
  return i < 0 ? (FONT_ORDER as readonly string[]).indexOf(' ') : i;
}
